declare module '@nlpjs/sentiment';
declare module '@nlpjs/core';
declare module '@nlpjs/core-loader';
declare module '@nlpjs/lang-en';
declare module '@nlpjs/language';
declare module '@nlpjs/nlp';
declare module '@nlpjs/nlu';
declare module '@nlpjs/evaluator';
declare module '@nlpjs/request';
